CREATE SCHEMA staging;
GO

CREATE TABLE staging.DatosCasoEstudio (
    [FECHA DE NACIMIENTO] NVARCHAR(MAX),
    [RUT] NVARCHAR(MAX),
    [NIVEL EDUCACIONAL DECLARADO] NVARCHAR(MAX),
    [SEXO] NVARCHAR(MAX),
    [ESTADO CIVIL] NVARCHAR(MAX),
    [ACTIVIDAD] NVARCHAR(MAX),
    [INGRESO MENSUAL PROMEDIO] NVARCHAR(MAX),
    [TOTAL DE CONTACTOS] NVARCHAR(MAX),
    [PUNTUACIÓN PROMEDIO] NVARCHAR(MAX),
    [REGIÓN] NVARCHAR(MAX),
    [FECHA APERTURA CUENTA] NVARCHAR(MAX),
    [USO DE TARJETA MENSUALMENTE] NVARCHAR(MAX),
    [SALDO MAXIMO REGISTRADO] NVARCHAR(MAX),
    [NUMERO DE CUENTA] NVARCHAR(MAX),
    [TIPO CUENTA] NVARCHAR(MAX),
    [VECES SALDO CERO] NVARCHAR(MAX)
);
